### ISSUE TITLE
PHP 8.1 Deprecated mysqli::escape_string(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by petrparolek** [nettrine/dbal#65] opened 2021-12-23 17:40 UTC
[exception--2021-12-23--18-34--77da3057dc.zip](https://github.com/nettrine/dbal/files/7770722/exception--2021-12-23--18-34--77da3057dc.zip)

![Screenshot 2021-12-23 at 18-41-28 System info](https://user-images.githubusercontent.com/6066243/147275402-84007073-ec8b-4732-9d3f-40d574196261.png)

**Comment by vody105** [comment] 2022-01-20 14:44
This is caused by `ProfilerLogger` used by Tracy panel. Seems like `$connection::quote` does not work with `null` values since php8.1

**Comment by petrparolek** [comment] 2022-02-09 12:08
Hlásím, že už mi vše již funguje na PHP 8.1, zřejmě to vyřešili v samotné Doctrine.

**Comment by foxycode** [comment] 2022-02-09 12:49
That's very good news. Wil try right away

**Comment by vody105** [comment] 2022-02-09 13:25
Still broken on latest doctrine v2

**Comment by Rixafy** [comment] 2022-05-13 21:50
Fixed for in 0.7 https://github.com/nettrine/dbal/pull/70 (in 0.8) it's also fixed in this PR https://github.com/nettrine/dbal/pull/69

**Closed** 2022-05-14 08:22 UTC
